name: Continuous Integration 

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10.6']
        # Replace 3.10.6 with 3.10 when mypy bug is fixed
        # https://github.com/python/mypy/issues/13627

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          python -m pip install tox-gh-actions
      - name: Run tests
        run: tox
      - name: Test docs can be built
        run: tox -e docs
